# Generated by Django 5.1.1 on 2024-10-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_user_imagenperfil_user_numerocelular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
