# Generated by Django 5.1.1 on 2024-10-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cantidad',
        ),
    ]
