# Generated by Django 5.1.1 on 2024-10-08 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
